apiVersion: v1
kind: Service
metadata:
  name: kubeservice
spec:
  selector:
    app: kubeecommerce
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedeploy
spec:
  replicas: 5
  selector:
    matchLabels: 
      app: kubeecommerce
  template:
    metadata:
      labels:
        app: kubeecommerce
    spec:
      containers:
        - name: kubecontainer
          image: kevinspigel/ecommerceserver:1.0.0
          ports: 
            - containerPort: 8080
          imagePullPolicy: Always
